apiVersion: 1
groups:
    - orgId: 1
      name: log-analyzer
      folder: Log Analyzer Alerts
      interval: 1m
      rules:
        - uid: cfgp0iv3hq6f4d
          title: Log Error Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: builder
                expr: log_levels_total{level="ERROR"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            description: Detected {{ $value }} ERROR logs from instance {{ $labels.instance }} (level={{ $labels.level }})
            summary: "\U0001F6A8 ERROR in logs: {{ $values.A }} errors"
          labels:
            service: log-analyzer
            severity: critical
          isPaused: false
          notification_settings:
            receiver: Telegram Alert
        - uid: bfgp0shs1we0wb
          title: Log Warning Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: builder
                expr: log_levels_total{level="WARNING"}
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            description: Detected {{ $value }} ERROR logs from instance {{ $labels.instance }} (level={{ $labels.level }})
            summary: '⚠️ WARNING in logs: {{ $values.A }} warnings'
          labels:
            service: log-analyzer
            severity: warning
          isPaused: false
          notification_settings:
            receiver: Telegram Alert
        - uid: efgp13auqjawwc
          title: Log Processing Error Alert
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: builder
                expr: log_errors_total
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            description: Detected {{ $value }} ERROR logs from instance {{ $labels.instance }} (level={{ $labels.level }})
            summary: "\U0001F525 Log processing errors: {{ $values.A }}"
          labels:
            service: log-analyzer
            severity: critical
          isPaused: false
          notification_settings:
            receiver: Telegram Alert
