#cloud-config
package_update: false
package_upgrade: false

runcmd:
  - [apt-get, update]
  - [apt-get, install, -y, docker.io, docker-compose-plugin, nginx, python3, python3-pip, git, curl]
  - [git, clone, "https://github.com/WaldemarZP/log-analyzer-devops.git", "/home/ubuntu/log-analyzer-devops"]
  - [bash, -c, "cd /home/ubuntu/log-analyzer-devops && pip3 install -r requirements.txt"]
  - [bash, -c, "cd /home/ubuntu/log-analyzer-devops && chmod +x deploy.sh && ./deploy.sh"]
  - [bash, -c, "cp /home/ubuntu/log-analyzer-devops/systemd/log-analyzer.service /etc/systemd/system/"]
  - [systemctl, daemon-reload]
  - [systemctl, enable, log-analyzer.service]
  - [systemctl, start, log-analyzer.service]
  - [systemctl, restart, nginx]

final_message: "Log Analyzer stack deployment completed"