#cloud-config
package_update: false
package_upgrade: false

packages:
  - curl

users:
  - name: ubuntu
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash

runcmd:
  - [curl, -s, -o, /tmp/deploy-cloud.sh, "https://raw.githubusercontent.com/WaldemarZP/log-analyzer-devops/main/deploy-cloud.sh"]
  - [chmod, +x, /tmp/deploy-cloud.sh]
  - [/tmp/deploy-cloud.sh]

final_message: "Log Analyzer cloud deployment completed"